theme: jekyll-theme-modernist
title: Robert Harvey's Code homepage
description: This page give an overview of the projects I have worked on and the lessons and technology I have learned

// change padding of headings
h1 {
    margin-top:2.5rem !important;
}

h2 {
    margin-top:2rem !important;
}

h3, h4 {
    margin-top:1.5rem !important;
}

p {
    margin-top:1rem !important;
    margin-bottom:1rem !important;
}

h1, h2, h3, h4 {
    font-weight: normal !important;
    margin-bottom:0.5rem !important;
}

pre {
    margin-bottom:1.5rem !important;
}
