theme: jekyll-theme-minimal
title: Robert Harvey's Code homepage
description: I am final year Undergraduate at Newcastle University, studying for a Masters degree in Computer Science. This site gives an overview and portal into the software projects I have delivered as part of this degree over the last 4 years.
